name = "EGGroupMakie"
uuid = "e944c24e-e3e5-4d5e-8fa5-a3772f1b1439"
authors = ["Jakob Hoffmann <jfb-hoffmann@hotmail.de> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
